### ISSUE TITLE
请求更新SDK

### ISSUE THREAD

**Issue by kj415j45** [kilingzhang/coolq-php-sdk#1]
coolq-http-api已经更新了几个版本了，导致SDK中部分方法的参数失效，例如sendPrivateMsg()方法的第三个参数is_raw已经更名为auto_escape

此外，希望能优先使用新提供的异步方法。

~~如果我有空的话会PR的~~

**Comment by kilingzhang** [comment]
现在正在更新sdk ~~重写~~  这周内应该会更新完成。感谢支持。🙊

**Comment by kj415j45** [comment]
重写就算了吧。。

我的bot面向过程写的（~~重写SDK我怕不是要改死~~

**Comment by kilingzhang** [comment]
做了向下兼容 不会有特别多的地方需要修改。 最后文档会说明的。

**Comment by kj415j45** [comment]
看了您的分支操作好迷啊 :v

**Comment by kj415j45** [comment]
完蛋了，我完全看不懂新版本的骚操作 :scream:

**Comment by kilingzhang** [comment]
umm　其实没改什么特别的　两个版本之间的差异我更新到文档中了 ~~还有些文档还没更新，如果有什么骚操作看不懂，可以私聊我ＱＱ:1353693508~~
