### ISSUE TITLE
收到CQ码,PHP怎么写能比较好的获取到信息,比如转成数组之类的?

### ISSUE THREAD

**Issue by iddddg** [kilingzhang/coolq-php-sdk#6]
如题，我现在是先用,号explode,再用=号explode，感觉很笨,求教

**Comment by iddddg** [comment]
补充一下CQ码的类型是rich

**Comment by kilingzhang** [comment]
一般我是通过正则匹配里面的cq码，然后根据type类型和值去进一步读取
如果你不想自己做操作可以在cqthhp中设置数组的形式返回。
https://cqhttp.cc/docs/4.2/#/Message

**Comment by iddddg** [comment]
好的谢谢,我去试试

**Comment by kilingzhang** [comment]
请问能发一下 rich 的CQ码吗  我这里没有例子

**Comment by iddddg** [comment]
[CQ:rich,url=https://url.cn/5zxAlDB,text=\n 饿了么拼手气，第7个领取的人得大红包 最高10元大红包，饿了么拼手气@你 \n]
我用数组格式很好取了,不过同样是饿了么APP分享出来的红包,有人rich,有人share,尴尬

**Comment by kilingzhang** [comment]
已添加
